### PR TITLE
add controller pizzaiago

### PR DESCRIPTION
**Pull request by iagoln**

### CODE REVIEW

**Review by devLeandroCoelho — COMMENTED** [review]
**Tudo ok...**

**Review by gabrieladaltoe — COMMENTED** [review]
ok.

**Review by Romsgs — COMMENTED** [review]
code review

**Review by gabrieladaltoe — APPROVED** [review]

**Review by Romsgs — APPROVED** [review]
approve

**Review by devLeandroCoelho — CHANGES_REQUESTED** [review]
Ta em branco favor revisar...

**Review by AlvesBelem — APPROVED** [review]
ok

**Review by P-Schil — APPROVED** [review]

**Pull request merged**
